# Generated by Django 4.1.2 on 2022-11-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0004_delete_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='customer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
