# Generated by Django 4.1.2 on 2022-11-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0005_customerprofile_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customerId',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
