# Generated by Django 4.1.2 on 2022-11-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0006_remove_customerprofile_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Office_supplies', 'Office supplies'), ('Home_Accessories/Supplies', 'Home Accessories/Supplies')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
