# Generated by Django 4.1.2 on 2022-11-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0008_payment_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
