# Generated by Django 4.1.2 on 2022-11-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0010_remove_item_category_customerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='name',
        ),
    ]
