# Generated by Django 4.1.2 on 2022-11-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0012_wallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
