# Generated by Django 4.1.2 on 2022-11-29 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainClient', '0013_remove_wallet_balance_alter_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='username',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
