# Generated by Django 4.1.2 on 2022-11-29 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainClient', '0014_wallet_balance_wallet_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
