# Generated by Django 4.1.2 on 2022-11-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0015_alter_wallet_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='username',
        ),
    ]
