# Generated by Django 4.1.2 on 2022-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0016_remove_wallet_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
