# Generated by Django 4.1.2 on 2022-12-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0017_alter_wallet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
