# Generated by Django 4.1.2 on 2022-12-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0018_items_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='customerId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainClient.customerprofile'),
        ),
    ]
