# Generated by Django 4.1.2 on 2022-12-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0019_wallet_customerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='customerId',
        ),
    ]
