# Generated by Django 4.1.2 on 2022-12-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0020_remove_wallet_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
