# Generated by Django 4.1.2 on 2022-12-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0022_adress_orderitems_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
