# Generated by Django 4.1.2 on 2023-01-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0026_remove_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='item',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='item',
            field=models.ManyToManyField(related_name='OrderItems', to='MainClient.items'),
        ),
    ]
