# Generated by Django 4.1.2 on 2023-01-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0027_remove_orderitems_item_orderitems_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
