# Generated by Django 4.1.2 on 2023-01-04 15:08

import MainClient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0029_remove_items_quantity_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='item',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='item',
            field=models.CharField(blank=True, max_length=100, verbose_name=MainClient.models.Items),
        ),
    ]
