# Generated by Django 4.1.2 on 2023-01-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainClient', '0032_alter_customerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='deneme',
        ),
    ]
